### ISSUE TITLE
Wtf?

### ISSUE THREAD

**Issue by tsebis** [neseleznev/Pumper#2]
Price become more by 25 % then in the beginning, stop ordering

**Comment by neseleznev** [comment]
Thanks for your response! This limitation was made for myself to stop my own greed during pumps sometimes :)
Certainly, it should be optional and documented; full control have to be up to you. Fixed this by latest commit, I'll roll it up with win installer in version 0.3
I'm sorry if you've lost a moment during pump because of this "feature". Good trading!

**Comment by tsebis** [comment]
i cannot change it myself for now?
